baseURL = 'https://donaldschulz.com/'
languageCode = 'en-us'
title = 'Donald Schulz Story: My Journey'
theme = "hugo-book"
[parms]
  BookSection = "*"
  BookToc = true
  BookTheme = 'auto'
  BookComments = false
  
